[package]
name = "qqbot-cmd"
version = "0.1.0"
edition = "2024"

[dependencies]
kovi = "0.11.10"
kovi-plugin-siliconflow = "0.1.1"
reply = { path = "../plugins/reply" }
apply-request={path = "../plugins/apply-request"}