[apply-request]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[apply-request.access_list]
friends = []
groups = []

[reply]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[reply.access_list]
friends = []
groups = []

[kovi-plugin-siliconflow]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-siliconflow.access_list]
friends = []
groups = []
