[apply-request]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[apply-request.access_list]
friends = []
groups = []

[cmd-reply]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[cmd-reply.access_list]
friends = []
groups = []
