name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev
    
    - name: Check formatting (non-blocking)
      run: cargo fmt --all -- --check
      continue-on-error: true
      
    - name: Run clippy (allow warnings)
      run: cargo clippy --all-targets --all-features
    
    - name: Build all targets
      run: cargo build --release --verbose
      
    - name: Run tests (non-blocking)
      run: cargo test --verbose
      continue-on-error: true
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qqbot-binaries-${{ github.sha }}
        path: |
          target/release/qqbot-cmd
        if-no-files-found: warn

